MY_APP_ID = "com.example.app"
SCHEME_DEV = "schemeDev"
SCHEME_PRODUCTION = "schemeProduction"

update_fastlane

default_platform(:ios)

platform :ios do

  desc "Define info account without 2FA can upload build to TestFlight"
  before_all do
    ENV["FASTLANE_DONT_STORE_PASSWORD"] = "1"
    ENV["FASTLANE_USER"] = "appleaccount@gmail.com"
    ENV["FASTLANE_PASSWORD"] = "Abc12345678*"
  end

  lane :getCer do
    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
  end
  
  lane :updateSigh do
    cert
    sigh(adhoc: true)
  end

  desc "upload to Beta by FireBase"
  lane :uploadFirebaseDev do
    firebase_app_distribution(
        app: "1:664452671234:ios:1234316d004bac5bf61234",
        testers: “TESTER-EMAILS”,
        groups: “TESTER-GROUP”,
        release_notes: "Version Staging",
        firebase_cli_token: "1//1234HjkYpldZ4CgYIARAAGBASNwF-1234whOlK0VPxN63LfLpqBG98TzhJ_1234v3e0mrE9PtCmketolYa7hhInJwj13UisBdEM",
    )
  end
  
  desc "install Cer And Provisioning"
  lane :installCerAndProvisioning do
    import_certificate(
      keychain_name: "login",
      certificate_path: "certs/dist.p12",
      certificate_password: "123123",
      keychain_password: "123123"
    )
    install_provisioning_profile(path: "certs/provisionAdhoc.mobileprovision")
    install_provisioning_profile(path: "certs/provisionAppStore.mobileprovision")
  end
  
  desc "Archive build Ad Hoc"
  lane :gymAppAdHoc do
    disable_automatic_code_signing
    update_project_provisioning(
      profile: "certs/provisionAdhoc.mobileprovision", 
      code_signing_identity: "Apple Distribution: Team Name (ABCDU8RR8X)"
    )
    gym(scheme: SCHEME_DEV,export_method: "ad-hoc")
  end

  desc "Archive build production with method app store"
  lane :buildAppProductionMethodAppStore do
    disable_automatic_code_signing
    update_project_provisioning(
      profile: "certs/provisionAppStore.mobileprovision", 
      code_signing_identity: "Apple Distribution: Team Name (ABCDU8RR8X)"
    )
    gym(scheme: SCHEME_PRODUCTION,export_method: "app-store")
  end

  desc "Upload build production to Test Flight"
  lane :uploadToTestFlight do
    pilot(skip_waiting_for_build_processing: true)
  end


  desc "Push a new build to Fabric and FireBase App Distribution"
  lane :uploadIPA do
  
    installCerAndProvisioning

    gymAppAdHoc

    uploadFirebaseDev

    buildAppProductionMethodAppStore

    uploadToTestFlight

  end


end
